#!/bin/bash
# Based on patches submitted by: Julien Valroff <julien@kirya.net>
# & "Tim Dijkstra \(tdykstra\)" <tim@famdijkstra.org>

. /usr/lib/pm-utils/functions

case "$1" in
	thaw|resume)
		invoke-rc.d sl-modem-daemon start
		;;
	hibernate|suspend)
		invoke-rc.d sl-modem-daemon stop
		;;
	*)
		;;
esac

exit $?
