#!/bin/sh

. /usr/share/debconf/confmodule

db_get sl-modem-daemon/country || true

if test -n "$RET" ; then
   perl -pe "s,^SLMODEMD_COUNTRY.*,SLMODEMD_COUNTRY=$RET," -i /etc/default/sl-modem-daemon
fi

if [ -x "/etc/init.d/sl-modem-daemon" ]; then
	update-rc.d sl-modem-daemon defaults 12 >/dev/null
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d sl-modem-daemon start || true
	else
		/etc/init.d/sl-modem-daemon start || true
	fi
fi

#DEBHELPER#

exit 0
